ALTER TABLE "Order"
ADD COLUMN IF NOT EXISTS "shippingMethod" TEXT NOT NULL DEFAULT 'INPOST_KURIER',
ADD COLUMN IF NOT EXISTS "shippingMethodName" TEXT NOT NULL DEFAULT 'InPost Kurier',
ADD COLUMN IF NOT EXISTS "shippingPrice" DOUBLE PRECISION NOT NULL DEFAULT 16.99,
ADD COLUMN IF NOT EXISTS "shippingPoint" TEXT,
ADD COLUMN IF NOT EXISTS "shippingEstimatedDelivery" TEXT NOT NULL DEFAULT '1-2 dni robocze';
